# Generated by Django 2.1.5 on 2019-01-19 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ayes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_taken',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
