# Generated by Django 2.1.5 on 2019-01-19 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
